/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_mouse_MouseHookJni */

#ifndef _Included_jni_mouse_MouseHookJni
#define _Included_jni_mouse_MouseHookJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_mouse_MouseHookJni
 * Method:    startMouseHook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_mouse_MouseHookJni_startMouseHook
  (JNIEnv *, jobject);

/*
 * Class:     jni_mouse_MouseHookJni
 * Method:    stopMouseHook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_mouse_MouseHookJni_stopMouseHook
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
