/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_keyboard_KeyboardHookJni */

#ifndef _Included_jni_keyboard_KeyboardHookJni
#define _Included_jni_keyboard_KeyboardHookJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_keyboard_KeyboardHookJni
 * Method:    startKeyboardHook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_keyboard_KeyboardHookJni_startKeyboardHook
  (JNIEnv *, jobject);

/*
 * Class:     jni_keyboard_KeyboardHookJni
 * Method:    stopKeyboardHook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_keyboard_KeyboardHookJni_stopKeyboardHook
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
